include: package:flutter_lints/flutter.yaml

linter:
  rules:
    always_declare_return_types
    avoid_catches_without_on_clauses
    avoid_equals_and_hash_code_on_mutable_classes
    avoid_types_on_closure_parameters
    cancel_subscriptions
    depend_on_referenced_packages
    directives_ordering
    eol_at_end_of_file
    omit_local_variable_types
    prefer_asserts_in_initializer_lists
    prefer_final_in_for_each
    prefer_final_locals
    prefer_null_aware_method_calls
    prefer_relative_imports
    prefer_single_quotes
    sort_constructors_first
    sort_pub_dependencies
    sort_unnamed_constructors_first
    type_annotate_public_apis
    unnecessary_lambdas
    unnecessary_parenthesis
    use_named_constants
    use_super_parameters
