name: wizard_router
description: >-
  Routing for linear wizards. No dependencies between pages. Pages merely
  request the next page. Routes and conditions defined in a central place.
homepage: https://github.com/jpnurmi/wizard_router
repository: https://github.com/jpnurmi/wizard_router
issue_tracker: https://github.com/jpnurmi/wizard_router/issues
version: 0.6.0

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  collection: ^1.15.0
  flow_builder: ^0.0.3
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
