name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
    - name: Get dependencies
      run: flutter pub get
    - name: Analyze
      run: flutter analyze
    - name: Format
      run: flutter format --set-exit-if-changed .
    - name: Publish dry-run
      run: flutter pub publish --dry-run

  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
    - name: Run tests
      run: flutter test --coverage
    - name: Upload coverage
      uses: codecov/codecov-action@v3
      with:
        file: coverage/lcov.info
        token: ${{secrets.CODECOV_TOKEN}}
