name: CI

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  analyze:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
      - run: flutter pub get
      - run: flutter analyze

  coverage:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - uses: subosito/flutter-action@v2
    - run: sudo apt update
    - run: sudo apt install -y lcov
      env:
        DEBIAN_FRONTEND: noninteractive
    - run: flutter test --coverage
    - uses: codecov/codecov-action@v3
      with:
        token: ${{secrets.CODECOV_TOKEN}}

  format:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
      - run: flutter pub get
      - run: flutter format --set-exit-if-changed .

  linux:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - uses: subosito/flutter-action@v2
    - run: sudo apt update
    - run: sudo apt install -y clang cmake curl libgtk-3-dev ninja-build pkg-config unzip xvfb
      env:
        DEBIAN_FRONTEND: noninteractive
    - run: flutter build linux -v
      working-directory: example

  pub:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
      - run: flutter pub get
      - run: flutter pub publish --dry-run

  test:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - uses: subosito/flutter-action@v2
    - run: flutter test

  web:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - uses: subosito/flutter-action@v2
    - run: flutter build web -v
      working-directory: example
